# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# Example config and default values
#
# [[item]]
# file = '~/.config/example' (file to inject to, supports tilde and env var expansion. required)
# template = 'example' (template to use. required)
# subtemplate = 'default' (subtemplate to use)
# rewrite = false (should we rewrite the entire file?)
# start = '# Start flavours' (if not rewriting, where to start replacing)
# end = '# End flavours' (if not rewriting, where to stop replacing)
# hook = '' (command to execute after injecting)
# light = true (whether this hook should be executed even when flavours apply is run with lightweight flag)
#
# Example for i3
#
# [[item]]
# file = '~/.config/i3/config'
# template = 'i3'
# subtemplate = 'colors'
# hook = 'i3-msg reload'
# rewrite = false
# light = false


[[item]]
file = '~/.i3/config'
template = 'i3'
subtemplate = 'colors'
hook = 'i3-msg reload'

[[item]]
file = '~/.config/alacritty/alacritty.yml'
template = 'alacritty'
subtemplate = 'default-256'

[[item]]
file = '~/.config/polybar/config'
template = 'polybar'
